theme: minima

include:
  - _layouts
  - _sass
  - _posts
  - assets

menu:
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Home
    url: /projects

# Site settings
title: Learning Curve