title: Statistical Journey
subtitle: The path of knowledge
description: A blog about statistics and epistemology

theme: minima
header_pages:
  - index.md
  - tutorial.md
  - about.md

social_links:
  - { platform: github,          user_url: "https://github.com/JosephBARBIERDARNAL" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/joseph-barbier-4ab531224/" }